### ISSUE TITLE
Non-characters are not specifically identified as such

### ISSUE THREAD

**Issue by SlySven** [ridiculousfish/widecharwidth#10]
Could we have another special return value added please for the 66 Unicode *Non-characters*?

See the second chunk of https://www.unicode.org/faq/private_use.html - as it is those codepoints are *valid* Unicode codepoints (may be used internally to an application) but though they do share the General_Category value Cn (Unassigned) with unassigned reserved code points in the standard they do have a different interpretation.

**Comment by ridiculousfish** [comment]
Seems reasonable to me. I wasn't aware that widecharwidth was being used outside of fish-shell, that's neat! May I ask what project it's being used in?

**Comment by vadi2** [comment]
We've been using it since June 2019 in https://github.com/Mudlet/Mudlet/blob/development/src/widechar_width.h, since we have a custom text display widget and needed to handle emojis :)

I think this issue in particular due to https://github.com/Mudlet/Mudlet/issues/4289 where an update to the shield emoji broke the display for us.

**Comment by SlySven** [comment]
Apart from anything else - you @ridiculousfish are keeping things up to date - whereas Markus Kuhn's `mk_wcwidth()`/`mk_wcwidth_cjk()` - from: https://www.cl.cam.ac.uk/~mgk25/ucs/wcwidth.c have not been updated since Unicode 5.0...

**Comment by vadi2** [comment]
@SlySven @ridiculousfish is this the same issue that Qt ran into https://bugreports.qt.io/browse/QTBUG-92822 ? They updated their UCD and things "suddenly" didn't work, because UCD removed some data, but it turns out they were missing an implementation of an algorithm all the way from Unicode 11. If they had the algorithm in place, the removal would not have affected them.

**Comment by SlySven** [comment]
Nope - it is nothing to do with that QT issue - this is about several groups of Unicode codepoints (66 in total in both the BMP and the supplementary ones) that have been permanently declared (in around Unicode 3.1 IIRC thought two originally was in the very first version) that they will NEVER be assigned to a grapheme - they are not *reserved* characters but instead they are *non-characters* - and all code that processes Unicode data must accept them as valid Unicode, but they do not have an assigned meaning. As such they may be used for *internal purposes* within an application...

... which is why I am eye-ing a few up for Mudlet's/my own purposes!

:smiling_imp:

**Comment by vadi2** [comment]
Ah ok. This is not about the issue then that we can't update to latest version of widecharwidth because it has regressions.

**Comment by ridiculousfish** [comment]
Fixed in 82e12385ad57b2fe6990249ebb2426da0e771330; now there is a new `widechar_non_character` constant.

**Comment by vadi2** [comment]
See https://github.com/ridiculousfish/widecharwidth/issues/11
